main: Add '--version' CLI flag
esp-rs/espmonitor pull request #49
Opened 2022-05-13 14:24 UTC by har7an

Prints the current version as defined in the `Cargo.toml`.

2022-05-13 17:53 UTC, kelnos requested changes

2022-05-13 17:53 UTC, kelnos commented on espmonitor/src/main.rs
> +    } else if args.contains("-v") || args.contains("--version") {
GNU standard is generally a _capital_ `V` for the short option.  (Lowercase `v` is used for `--verbose`.)

2022-05-13 17:54 UTC, kelnos commented
Thanks for this!  Probably should just move to a more full-featured command line parser like `clap` that does all this for us, but this is great for now.  Just one small change and I'm happy to merge.

2022-05-13 17:55 UTC, kelnos commented
Oh -- it looks like the cargo integration doesn't do this by itself, so if you'd be interested in adding it there as well, that'd be great.

2022-05-16 06:48 UTC, har7an commented
Thanks for the feedback. I added the requested change and copied the same code to the cargo-esptools. I also updated the usage message to reflect the new `--version` option.

2022-05-16 06:49 UTC, har7an commented
> Probably should just move to a more full-featured command line parser like `clap` that does all this for us

I've got some experience with clap. Shall I go ahead and try to add this?

2022-05-17 01:42 UTC, kelnos commented
Ok, we're working on an impl with `clap` now, so I guess we can close this out.

2022-05-17 01:42 UTC, closed without merging